# Generated by Django 5.2.6 on 2025-10-01 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('problem_id', models.IntegerField(db_index=True)),
                ('category', models.IntegerField(db_index=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=64, null=True)),
                ('pixel_ratio', models.FloatField(blank=True, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('logical_width', models.IntegerField(blank=True, null=True)),
                ('logical_height', models.IntegerField(blank=True, null=True)),
                ('css_width', models.IntegerField(blank=True, null=True)),
                ('css_height', models.IntegerField(blank=True, null=True)),
                ('zoom', models.FloatField(blank=True, null=True)),
                ('pan_x', models.IntegerField(blank=True, null=True)),
                ('pan_y', models.IntegerField(blank=True, null=True)),
                ('supports_pressure', models.BooleanField(default=False)),
                ('supports_tilt', models.BooleanField(default=False)),
                ('supports_twist', models.BooleanField(default=False)),
                ('supports_coalesced', models.BooleanField(default=False)),
                ('stroke_count', models.IntegerField()),
                ('total_distance_px', models.FloatField()),
                ('average_stroke_length_px', models.FloatField(blank=True, null=True)),
                ('undo_count', models.IntegerField(default=0)),
                ('redo_count', models.IntegerField(default=0)),
                ('eraser_count', models.IntegerField(default=0)),
                ('zoom_count', models.IntegerField(default=0)),
                ('pan_count', models.IntegerField(default=0)),
                ('tool_change_count', models.IntegerField(default=0)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('label', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('stroke_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=16)),
                ('stroke_width', models.IntegerField()),
                ('start_ms', models.IntegerField()),
                ('end_ms', models.IntegerField()),
                ('pointer_type', models.CharField(default='pen', max_length=16)),
                ('is_coalesced', models.BooleanField(default=False)),
                ('total_distance_px', models.FloatField()),
                ('average_speed_pxps', models.FloatField(blank=True, null=True)),
                ('average_pressure', models.FloatField(blank=True, null=True)),
                ('bbox_min_x', models.IntegerField()),
                ('bbox_min_y', models.IntegerField()),
                ('bbox_max_x', models.IntegerField()),
                ('bbox_max_y', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='api.session')),
            ],
            options={
                'db_table': 'strokes',
            },
        ),
        migrations.CreateModel(
            name='StrokePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('t_ms', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('tilt_x', models.IntegerField(blank=True, null=True)),
                ('tilt_y', models.IntegerField(blank=True, null=True)),
                ('twist', models.IntegerField(blank=True, null=True)),
                ('pointer_type', models.CharField(max_length=16)),
                ('pointer_id', models.IntegerField(blank=True, null=True)),
                ('buttons', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.session')),
                ('stroke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.stroke')),
            ],
            options={
                'db_table': 'stroke_points',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts_ms', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('details', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.session')),
            ],
            options={
                'db_table': 'events',
                'indexes': [models.Index(fields=['session', 'ts_ms'], name='events_session_2134ed_idx'), models.Index(fields=['type'], name='events_type_671f92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stroke',
            index=models.Index(fields=['session', 'start_ms'], name='strokes_session_48b226_idx'),
        ),
        migrations.AddIndex(
            model_name='strokepoint',
            index=models.Index(fields=['session', 'stroke', 'idx'], name='stroke_poin_session_670a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='strokepoint',
            index=models.Index(fields=['session', 't_ms'], name='stroke_poin_session_532fe3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strokepoint',
            unique_together={('stroke', 'idx')},
        ),
    ]
